---
- name: Install Git
  package:
    name: git
    state: present

- name: Configure Git username
  git_config:
    name: user.name
    scope: global
    value: "{{ git_username }}"

- name: Configure Git email
  git_config:
    name: user.email
    scope: global
    value: "{{ git_email }}"

- name: Generate SSH key
  openssh_keypair:
    path: "~/.ssh/id_rsa"
    type: rsa
    size: 4096
    state: present

- name: Display public SSH key
  command: cat ~/.ssh/id_rsa.pub
  register: ssh_public_key

- name: Show SSH public key
  debug:
    msg: "Add this SSH key to your GitHub account: {{ ssh_public_key.stdout }}"