- name: download go tar file
  command: wget https://go.dev/dl/go{{version}}.linux-amd64.tar.gz
 
- name: Delete previous installation
  command: rm -rf /usr/local/go
  become: true
 
- name: Extract and move new go folder to /usr/local
  command: tar -C /usr/local -xzf go{{version}}.linux-amd64.tar.gz
  become: true
 
- name: Delete downloaded tar file
  shell: rm -rf go{{version}}.linux-amd64.tar.gz*

- name: Add go binary path to .zshrc
  ansible.builtin.lineinfile:
    path: "/home/johannes/.zshrc"
    line: 'export PATH=$PATH:/usr/local/go/bin:$GOPATH/bin'
    insertafter: "EOF"

- name: Source updated profile and test go version
  ansible.builtin.shell: 
    cmd: . source /home/johannes/.zshrc && go version
