---
  - name: "Setting up Go"
    vars:
      -version: 1.22.2
    tasks:
      - name: "Downloading go"
        command: wget https://go.dev/dl/go{{version}}.linux-amd64.tar.gz

      - name: "Remove previous version"
        command: rm -rf /usr/local/go
        become: true
      
      - name: "Extracting and moving new go version to folder"
        command: tar -C /usr/local -xzf go{{version}}.linux-amd64.tar.gz
        become: true
    
      - name: "Delete downloaded tar file"
        shell: rm -rf go{{version}}.linux-amd64.tar.gz*
      
      - name: "Setting go path"
        lineinfile:
          path: ~/.zshrc
          line: 'export GOPATH=$HOME/go'
          line: 'export PATH=$PATH:/usr/local/go/bin:$GOPATH/bin'
          create: true
          state: present
      
      - name: "Source ZSHRC and test GO"
        shell: .~/.zshrc && go version

