---
- name: Install Homebrew
  import_tasks: install_homebrew.yml

- name: Install Visual Studio Code
  import_tasks: install_vscode.yml

- name: Install Docker
  import_tasks: install_docker.yml

- name: Install Go
  import_tasks: install_go.yml

- name: Insall Nvim
  import_tasks: install_nvim
